
server:
  port: 8081

spring:
  application:
    name: API-GATEWAY
  cloud:
    gateway: #configuring gate way
      routes:
        - id: RECRUITMENT-SERVICE #using eureka service
          uri: lb://RECRUITMENT-SERVICE
          predicates:
            - Path=/recruitment/**

  autoconfigure: #for spring cloud
    exclude: org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration


eureka:  #for eureka, gateway is also a service, have to be registered in eureka server
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost