
server:
  port: 8081

spring:
  application:
    name: API-GATEWAY
  cloud:
    gateway:
      routes:
        - id: RECRUITMENT-SERVICE
          uri: lb://RECRUITMENT-SERVICE
          predicates:
            - Path=/recruitment/**



eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost